### PR TITLE
Redefined routes and used appropriate controllers. Also included views

### PR DESCRIPTION
**Pull request by muarachmann**
@lehone-hp you way of citing the callback functions in the web.oho is not appropriate. I passed it via a controller using the `php artisan make:controller` command. That should do the trick. Also no need for saying `{{  route('home') }}`  for example you could just do this  `/home`. Take a look at it. If you have any doubt i will show you. Thanks

### CODE REVIEW

**Comment by lehone-hp** [comment]
Yeah I didn't want to use controllers cus I didn't know which controllers we were going to be using. That's why I just made the callbacks in the web.php file.

**Comment by lehone-hp** [comment]
As for the routes, I think it is advisable to name them and reference them by name in case we want to change the urls tomorrow. That way we just have to change the urls only in the web.php file and it gets reflected throughout the entire project.

**Comment by muarachmann** [comment]
ok i will place a name on the and re-commit

**Comment by muarachmann** [comment]
I guess thats all i have to do with this PR. the routes. Also i stripped off css and js yields. IMO they will have no conflicts and will all be extended from `app.blade`. 
### Methodology

- [x] The PagesController will handle all static 
- [x] CartController will be responsible for all related cart issues.
.... etc

Also you might want to look for a small dashboard theme for the client section where they will be able to see their accounts, manage orders, see transactions & notifications if any.

I will do same for the admin section. Once this is merged you can handle the client and front view till checkout . I will handle the admin section. Pulling up a theme probably today or tomorrow

**Pull request merged**
